version: "3"
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    networks:
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.postiva.entrypoints=websecure"
      - "traefik.http.routers.postiva.tls.certResolver=letsencrypt"
      - "traefik.http.routers.postiva.rule=Host(`next.postiva.app`)"
      - "traefik.http.services.postiva.loadbalancer.server.port=8000"
    ports:
      - 8000:8000

networks:
  dokploy-network:
    external: true